meta:
  generations: 1000
  representation: "path"
  elitism: true
  crossover: 
    probability: 0.6
    type: "OX"
  mutation:
    probability: 0.1
    type: "inversion"
data:
  - name: "Kyiv"
    x: 100
    y: 100
  - name: "Zaporizhzhya"
    x: 500
    y: 400
random:
  canvas:
    width: 1000
    height: 1000
  names: ["Kyiv", "Lviv", "Zaporizhzhya", "Dnipro", "Mariupol"]