meta:
  generations: 1000
  representation: "path"
  elitism: true
  crossover: 
    probability: 0.6
    type: "PBC"
  mutation:
    probability: 0.2
    type: "transposition"
  view:
    history: 
      show: true
      delay: 500ms
data:
  - name: "Kyiv"
    x: 100
    y: 100
  - name: "Zaporizhzhya"
    x: 500
    y: 400
  - name: "Mariupol"
    x: 200
    y: 250
  - name: "Lviv"
    x: 150
    y: 300
  - name: "Dnipro"
    x: 400
    y: 350
  - name: "Charkiv"
    x: 450
    y: 230
  - name: "Ternopil"
    x: 350
    y: 440
  - name: "New York"
    x: 350
    y: 120
  - name: "Irpin"
    x: 40
    y: 140
  - name: "Enerhodar"
    x: 490
    y: 190
random:
  canvas:
    width: 1000
    height: 1000
  names: ["Kyiv", "Lviv", "Zaporizhzhya", "Dnipro", "Mariupol", "Bakhmut", "Melitopol", "Chmelnytskyi", "Zhytomyr", "Ternopol"]
